services:
  backend:
    build:
      context: ../../
      dockerfile: apps/backend/.docker/Dockerfile
    volumes:
      - ./:/build_/apps/backend
    environment:
      PORT: ${PORT}
      API_BASE_URL: ${API_BASE_URL}
      AWS_KEY: ${AWS_KEY}
      AWS_SECRET: ${AWS_SECRET}
      AWS_BUCKET_NAME: ${AWS_BUCKET_NAME}
      REGION: ${REGION}
      NODE_ENV: ${NODE_ENV}
    ports:
      - ${PORT}:${PORT}
