name: Backend Format

on:
  push:
    branches: [main]
    paths:
      - 'apps/backend/**'
      - '.github/workflows/backend-format.yml'
  pull_request:
    branches: [main]
    paths:
      - 'apps/backend/**'
      - '.github/workflows/backend-format.yml'
  workflow_dispatch:

jobs:
  format-check:
    name: Format Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Biome
        uses: biomejs/setup-biome@v1
        with:
          version: latest

      - name: Check formatting
        run: npx @biomejs/biome check apps/backend/src

      - name: Check linting
        run: npx @biomejs/biome lint apps/backend/src

  auto-format:
    name: Auto Format
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Biome
        uses: biomejs/setup-biome@v1
        with:
          version: latest

      - name: Format code
        run: npx @biomejs/biome check --write apps/backend/src

      - name: Fix linting issues
        run: npx @biomejs/biome lint --write apps/backend/src

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff --quiet && git diff --staged --quiet || git commit -m "style: auto-format backend code"
          git push
