name: Backend Dependency Update

on:
  schedule:
    # Run every day at 9 AM UTC
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  check-dependencies:
    name: Check Dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Check for outdated packages
        run: |
          echo "Checking for outdated packages..."
          npm outdated --workspace=apps/backend || echo "No outdated packages found"

      - name: Check for security vulnerabilities
        run: npm audit --audit-level=moderate --workspace=apps/backend

  update-dependencies:
    name: Update Dependencies
    runs-on: ubuntu-latest
    needs: check-dependencies
    if: github.event_name == 'workflow_dispatch'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Update dependencies
        run: |
          cd apps/backend
          npm update
          npm audit fix

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff --quiet && git diff --staged --quiet || git commit -m "chore: update backend dependencies"
          git push

  create-update-pr:
    name: Create Update PR
    runs-on: ubuntu-latest
    needs: check-dependencies
    if: github.event_name == 'schedule'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Create update branch
        run: |
          git checkout -b chore/update-dependencies-$(date +%Y%m%d)

      - name: Update dependencies
        run: |
          cd apps/backend
          npm update
          npm audit fix

      - name: Check if there are changes
        id: check_changes
        run: |
          if git diff --quiet; then
            echo "no_changes=true" >> $GITHUB_OUTPUT
          else
            echo "no_changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push changes
        if: steps.check_changes.outputs.no_changes == 'false'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "chore: update backend dependencies"
          git push origin HEAD

      - name: Create Pull Request
        if: steps.check_changes.outputs.no_changes == 'false'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "chore: update backend dependencies"
          body: |
            This PR updates backend dependencies to their latest versions.

            ## Changes
            - Updated npm packages to latest compatible versions
            - Fixed security vulnerabilities

            ## Testing
            - [ ] Run tests locally
            - [ ] Check for breaking changes
            - [ ] Verify application still works

            Auto-generated by GitHub Actions.
          branch: chore/update-dependencies-$(date +%Y%m%d)
          base: develop
          delete-branch: true
